name: Lint/Spellcheck
on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           submodules: "recursive"
#       - uses: pnpm/action-setup@v4
#         name: Install pnpm
#         with:
#           version: latest
#         id: pnpm-install
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#         #   cache: pnpm
#       - name: Install dependencies
#         run: pnpm install --no-frozen-lockfile
#       - name: Build
#         run: pnpm run build
#         env:
#           NITRO_PRESET: github_pages
#           NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: .output/public/

#   deploy:
#     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4.0.5

  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - uses: oven-sh/setup-bun@v2
            with:
                bun-version: latest
          - name: Install
            run: bun install
          - name: Lint
            run: bun run lint-ci
          - name: Spellcheck
            run: bun run spellcheck
